export const ASCENDENTE = 'ascendente'
export const DESCENDENTE = 'descendente'
export const FUERTE = 'fuerte'
export const DEBIL = 'debil'
export const VELOZ = 'veloz'
export const NOVELOZ = 'NOVELOZ'